# Site settings
title: Západ? Východ?
email: kubik.michal@hotmail.com
url: https://myso87.github.io
description: "Jeden kus Záhoraka a jeden kus Vychodniarky sa kdesi kedysi stretli a tam to začalo... Ako to pokračuje?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: instagram
    url: 
  - title: github
    url: https://github.com/myso87

# Build settings
markdown: kramdown
permalink: pretty
